export default {
    SET_COURSES_FAILED: "SET_COURSES_FAILED",
    SET_CURRENT_COURSE_FAILED: "SET_CURRENT_COURSE_FAILED",

    GET_LIST_CHAPTERS_FAILED: 'GET_LIST_CHAPTERS_FAILED',
    GET_CHAPTER_INFO_FAILED: 'GET_CHAPTER_INFO_FAILED',

    GET_LESSON_FAILED: 'GET_LESSON_FAILED',
}